---
- name: Test Azure VM connetivity
  hosts: all
  become: true

  tasks:
    - command: whoami
      register: user_info
    - name: Display output
      debug:
        var: user_info.stdout
    - name: Create User aaher
      user:
        name: aaher
        state: present
    - name: check aaher user exists
      command: id aaher
      register: user_check
    - name: Display user details
      debug: 
        var: user_check.stdout

