---
- name: Test Azure VM connetivity
  hosts: all
  become: true

  tasks:
    - command: whoami
    - name: Ping Test
      ping: 
    - name: Create User aaher
      user:
        name: aaher
        state: present
